@extends('layouts.app')

@section('content')
  <div class="d-flex justify-content-between align-items-center mb-3">
    <div>
      <h1 class="h3 mb-1">Notifications</h1>
      <p class="text-muted mb-0">Review alerts generated by rules, filings, and team activity.</p>
    </div>
    <div class="btn-group" role="group" aria-label="Filter">
      <button type="button" class="btn btn-outline-secondary active">All</button>
      <button type="button" class="btn btn-outline-secondary">Unread</button>
      <button type="button" class="btn btn-outline-secondary">Assigned to me</button>
    </div>
  </div>

  <div class="row g-3">
    <div class="col-lg-4">
      <div class="card h-100">
        <div class="card-header">Summary</div>
        <div class="card-body">
          <p class="mb-1"><strong>5</strong> unread alerts</p>
          <p class="mb-1"><strong>2</strong> items due this week</p>
          <p class="mb-3"><strong>1</strong> requires approval</p>
          <button type="button" class="btn btn-primary w-100">Mark all as read</button>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card h-100">
        <div class="list-group list-group-flush">
          <div class="list-group-item">
            <div class="d-flex justify-content-between">
              <div>
                <h2 class="h6 mb-1">Bank feed import completed</h2>
                <p class="text-muted mb-1">12 transactions were imported from Mizuho Checking ending in 5091.</p>
                <small class="text-muted">Today at 09:15</small>
              </div>
              <span class="badge text-bg-success">Info</span>
            </div>
          </div>
          <div class="list-group-item">
            <div class="d-flex justify-content-between">
              <div>
                <h2 class="h6 mb-1">Tax filing deadline approaching</h2>
                <p class="text-muted mb-1">Corporate income tax return is due in 7 days. Draft is at 65% complete.</p>
                <small class="text-muted">Yesterday at 17:40</small>
              </div>
              <span class="badge text-bg-warning">Reminder</span>
            </div>
          </div>
          <div class="list-group-item">
            <div class="d-flex justify-content-between">
              <div>
                <h2 class="h6 mb-1">Ledger approval requested</h2>
                <p class="text-muted mb-1">Mai Sato requested approval for expenses ledger adjustments.</p>
                <small class="text-muted">Yesterday at 11:22</small>
              </div>
              <span class="badge text-bg-primary">Action</span>
            </div>
            <div class="mt-3">
              <button class="btn btn-sm btn-outline-primary me-2">Approve</button>
              <button class="btn btn-sm btn-outline-secondary">View changes</button>
            </div>
          </div>
          <div class="list-group-item">
            <div class="d-flex justify-content-between">
              <div>
                <h2 class="h6 mb-1">Recurring entry paused</h2>
                <p class="text-muted mb-1">Monthly rent auto-posting failed because the ledger is locked for closing.</p>
                <small class="text-muted">2 days ago</small>
              </div>
              <span class="badge text-bg-danger">Alert</span>
            </div>
            <div class="mt-3">
              <button class="btn btn-sm btn-outline-danger">Resolve</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
